server: "hub-cloud.browserstack.com"

common_caps:
  "build": "capybara-browserstack"
  "browserstack.debug": true

browser_caps:
  -
    "project": "FolkOnTheHill"
    "browser": "IE"
    "browserstack.local": true
